services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres/contadorprimos
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: contadorprimos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password